// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdk96nQIMMWNynJsno5it3QfAtPErTA-A',
    appId: '1:768021781260:web:497a679a6bcb0687cfc729',
    messagingSenderId: '768021781260',
    projectId: 'flutter-news-hub-idoc',
    authDomain: 'flutter-news-hub-idoc.firebaseapp.com',
    storageBucket: 'flutter-news-hub-idoc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoQwqGY34i76lIWaEtnwvkgU--vQYEnbk',
    appId: '1:768021781260:android:ba763acacc0a7db2cfc729',
    messagingSenderId: '768021781260',
    projectId: 'flutter-news-hub-idoc',
    storageBucket: 'flutter-news-hub-idoc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6EFdAFCnLIA2BQ-CSZo4dNvDcgn5P2KA',
    appId: '1:768021781260:ios:25315ffb7643bf6ccfc729',
    messagingSenderId: '768021781260',
    projectId: 'flutter-news-hub-idoc',
    storageBucket: 'flutter-news-hub-idoc.appspot.com',
    iosBundleId: 'com.example.flutterNewsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6EFdAFCnLIA2BQ-CSZo4dNvDcgn5P2KA',
    appId: '1:768021781260:ios:c79542142596478bcfc729',
    messagingSenderId: '768021781260',
    projectId: 'flutter-news-hub-idoc',
    storageBucket: 'flutter-news-hub-idoc.appspot.com',
    iosBundleId: 'com.example.flutterNewsHub.RunnerTests',
  );
}
